export default {
  "seats": [
    {
      "width": 1,
      "fare": "",
      "zIndex": 0,
      "number": "A1",
      "type": "A1",
      "serviceTaxAmount": "0",
      "convenience_charge": "0",
      "commission": "",
      "operatorServiceChargeAbsolute": "",
      "operatorServiceChargePercent": "0",
      "totalFareWithTaxes": "",
      "ladiesSeat": "",
      "bookedBy": "",
      "ac": "true",
      "sleeper": "",
      "serviceTaxPer": "0",
      "available": "",
      "length": 1,
      "id": "A1",
      "seatid": "A1",
      "row": 0,
      "column": 1
    },
    {
      "width": 1,
      "fare": "1000",
      "zIndex": 0,
      "number": "A3",
      "type": "A3",
      "serviceTaxAmount": "0",
      "convenience_charge": "0",
      "commission": "",
      "operatorServiceChargeAbsolute": "",
      "operatorServiceChargePercent": "0",
      "totalFareWithTaxes": "1000",
      "ladiesSeat": "",
      "bookedBy": "",
      "ac": "true",
      "sleeper": "",
      "serviceTaxPer": "0",
      "available": "1",
      "length": 1,
      "id": "A3",
      "seatid": "A3",
      "row": 2,
      "column": 1
    }
  ]
}
